arch: amd64
os: linux
dist: focal
language: python

matrix:
  include:
    - env: CC=gcc
    - env: CC=clang

install:
  - pip3 install meson ninja
  - sudo apt-get -y install valgrind libvulkan-dev libvulkan1 vulkan-utils glslang-tools
    libxkbcommon-dev libwayland-dev libxcb1-dev wayland-protocols libxcb-ewmh-dev
    libxcb-icccm4-dev libxcb-shm0-dev libxcb-present-dev libxcb-xinput-dev libxcb-xkb-dev
    libxkbcommon-x11-dev libx11-dev libx11-xcb-dev

script:
  # TODO: fetch x11 deps
  - meson build -Dwith_x11=false
  - ninja -C build
  # yeah, we can't test it, sadly.
  # Would need provided GPUs for that (or a CPU implementation but
  # I won't spend months trying to get this running on travis...)

